import { NextRequest, NextResponse } from 'next/server'

export async function POST(request: NextRequest) {
  try {
    const { title, organization, sections, metadata } = await request.json()

    // Generate HTML content for PDF
    const htmlContent = generatePdfHtml(title, organization, sections, metadata)

    // For now, return the HTML as a downloadable file
    // In production, you'd use a library like puppeteer or a service like html-pdf-node
    
    // Simple text-based PDF generation using basic formatting
    const textContent = generateTextContent(title, organization, sections, metadata)
    
    return new NextResponse(textContent, {
      headers: {
        'Content-Type': 'text/plain',
        'Content-Disposition': `attachment; filename="${title.replace(/\s+/g, '_')}.txt"`,
      },
    })
  } catch (error) {
    console.error('PDF generation error:', error)
    return NextResponse.json({ error: 'Failed to generate PDF' }, { status: 500 })
  }
}

function generateTextContent(
  title: string,
  organization: string,
  sections: Array<{ title: string; content: string }>,
  metadata: { sector: string; standard: string; category: string }
): string {
  const divider = '═'.repeat(60)
  const thinDivider = '─'.repeat(60)
  
  let content = `
${divider}
${title.toUpperCase()}
${divider}

Organization: ${organization}
Sector: ${metadata.sector}
Standard: ${metadata.standard}
Document Type: ${metadata.category}
Generated: ${new Date().toLocaleDateString('en-AU')}

${divider}

`

  sections.forEach((section) => {
    content += `
${section.title.toUpperCase()}
${thinDivider}

${section.content}

`
  })

  content += `
${divider}
END OF DOCUMENT
${divider}

This document was generated by Kwooka Compliance System.
For compliance tracking and analysis, upload this document to your Documents library.

© ${new Date().getFullYear()} ${organization}. All rights reserved.
`

  return content
}

function generatePdfHtml(
  title: string,
  organization: string,
  sections: Array<{ title: string; content: string }>,
  metadata: { sector: string; standard: string; category: string }
): string {
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${title}</title>
  <style>
    @page {
      margin: 2cm;
      @bottom-center {
        content: "Page " counter(page) " of " counter(pages);
        font-size: 10px;
        color: #666;
      }
    }
    body {
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      font-size: 11pt;
      line-height: 1.6;
      color: #333;
    }
    .header {
      text-align: center;
      border-bottom: 3px solid #f97316;
      padding-bottom: 20px;
      margin-bottom: 30px;
    }
    .header h1 {
      color: #f97316;
      font-size: 24pt;
      margin: 0 0 10px 0;
    }
    .header .org {
      font-size: 14pt;
      color: #666;
    }
    .metadata {
      background: #f8f9fa;
      border: 1px solid #e9ecef;
      border-radius: 8px;
      padding: 15px;
      margin-bottom: 30px;
    }
    .metadata table {
      width: 100%;
      border-collapse: collapse;
    }
    .metadata td {
      padding: 5px 10px;
    }
    .metadata .label {
      font-weight: bold;
      color: #666;
      width: 150px;
    }
    .section {
      margin-bottom: 25px;
      page-break-inside: avoid;
    }
    .section h2 {
      color: #1e293b;
      font-size: 14pt;
      border-bottom: 2px solid #f97316;
      padding-bottom: 8px;
      margin-bottom: 15px;
    }
    .section-content {
      white-space: pre-wrap;
    }
    ul, ol {
      margin-left: 20px;
    }
    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #e9ecef;
      text-align: center;
      font-size: 9pt;
      color: #666;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>${title}</h1>
    <div class="org">${organization}</div>
  </div>
  
  <div class="metadata">
    <table>
      <tr>
        <td class="label">Sector:</td>
        <td>${metadata.sector}</td>
        <td class="label">Standard:</td>
        <td>${metadata.standard}</td>
      </tr>
      <tr>
        <td class="label">Document Type:</td>
        <td>${metadata.category}</td>
        <td class="label">Generated:</td>
        <td>${new Date().toLocaleDateString('en-AU')}</td>
      </tr>
    </table>
  </div>
  
  ${sections.map(section => `
    <div class="section">
      <h2>${section.title}</h2>
      <div class="section-content">${formatContent(section.content)}</div>
    </div>
  `).join('')}
  
  <div class="footer">
    <p>This document was generated by Kwooka Compliance System</p>
    <p>© ${new Date().getFullYear()} ${organization}. All rights reserved.</p>
  </div>
</body>
</html>
  `
}

function formatContent(content: string): string {
  // Convert markdown-style formatting to HTML
  return content
    .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
    .replace(/\n•/g, '\n<br>•')
    .replace(/\n\d+\./g, (match) => `\n<br>${match.trim()}`)
    .replace(/\n\n/g, '</p><p>')
    .replace(/\n/g, '<br>')
}